apiVersion: apps/v1
kind: Deployment
metadata:
  name: metricity
  namespace: bots
spec:
  replicas: 1
  selector:
    matchLabels:
      app: metricity
  template:
    metadata:
      labels:
        app: metricity
    spec:
      securityContext:
        fsGroup: 2000
        runAsUser: 1000
        runAsNonRoot: true
      containers:
        - name: metricity
          image: ghcr.io/python-discord/metricity:latest
          imagePullPolicy: "Always"
          envFrom:
            - secretRef:
                name: metricity-env
          securityContext:
            readOnlyRootFilesystem: true
