"""
enable cascade deletion for messages.

Revision ID: 38085c8f1099
Revises: abc065ff2fb3
Create Date: 2020-08-25 13:00:21.629836

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "38085c8f1099"
down_revision = "abc065ff2fb3"
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Apply the current migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("messages_author_id_fkey", "messages", type_="foreignkey")
    op.drop_constraint("messages_channel_id_fkey", "messages", type_="foreignkey")
    op.create_foreign_key(None, "messages", "users", ["author_id"], ["id"], ondelete="CASCADE")
    op.create_foreign_key(None, "messages", "channels", ["channel_id"], ["id"], ondelete="CASCADE")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert the current migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "messages", type_="foreignkey")
    op.drop_constraint(None, "messages", type_="foreignkey")
    op.create_foreign_key("messages_channel_id_fkey", "messages", "channels", ["channel_id"], ["id"])
    op.create_foreign_key("messages_author_id_fkey", "messages", "users", ["author_id"], ["id"])
    # ### end Alembic commands ###
