"""
Add public flags column.

Revision ID: 45973dacf7da
Revises: 451f61f7f7cb
Create Date: 2020-09-02 10:38:18.142271

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "45973dacf7da"
down_revision = "451f61f7f7cb"
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Apply the current migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("public_flags", sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert the current migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "public_flags")
    # ### end Alembic commands ###
