"""
initial migration.

Revision ID: 4d293b37634c
Revises:
Create Date: 2020-08-25 03:09:13.565389

"""


# revision identifiers, used by Alembic.
revision = "4d293b37634c"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Apply the current migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert the current migration."""
