"""Add support for threads

Revision ID: 563a15b2a76e
Revises: d6c9452c3940
Create Date: 2021-10-31 14:46:49.926646

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '563a15b2a76e'
down_revision = 'd6c9452c3940'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'threads',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('parent_channel_id', sa.String(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('archived', sa.Boolean(), nullable=False),
        sa.Column('auto_archive_duration', sa.Integer(), nullable=False),
        sa.Column('locked', sa.Boolean(), nullable=False),
        sa.Column('type', sa.String(), nullable=False),
        sa.ForeignKeyConstraint(['parent_channel_id'], ['channels.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.add_column('messages', sa.Column('thread_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_messages_thread_id'), 'messages', ['thread_id'], unique=False)
    op.create_index(op.f('ix_threads_type'), 'threads', ['type'], unique=False)
    op.create_foreign_key(None, 'messages', 'threads', ['thread_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_index(op.f('ix_messages_thread_id'), table_name='messages')
    op.drop_column('messages', 'thread_id')
    op.drop_table('threads')
    # ### end Alembic commands ###
