"""
add in_guild column.

Revision ID: 5683123ff89a
Revises: 2743389eb63e
Create Date: 2020-08-25 19:57:41.958297

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "5683123ff89a"
down_revision = "2743389eb63e"
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Apply the current migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("in_guild", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert the current migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "in_guild")
    # ### end Alembic commands ###
