"""Remove opt_out column

Revision ID: 911049796159
Revises: 408aac572bff
Create Date: 2021-04-09 05:09:28.565384

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '911049796159'
down_revision = '408aac572bff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'opt_out')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('opt_out', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
