"""
remove verified columns.

Revision ID: a259ab5efcec
Revises: 2faa292e5818
Create Date: 2020-12-19 22:44:27.897133

"""
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "a259ab5efcec"
down_revision = "2faa292e5818"
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Apply the current migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "is_verified")
    op.drop_column("users", "verified_at")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert the current migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("verified_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column("users", sa.Column("is_verified", sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
