"""
Add verified_at column.

Revision ID: aa3517f1b1bd
Revises: 45973dacf7da
Create Date: 2020-09-12 02:34:11.722267

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "aa3517f1b1bd"
down_revision = "45973dacf7da"
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Apply the current migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("verified_at", sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert the current migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "verified_at")
    # ### end Alembic commands ###
