"""
add bot column to user table.

Revision ID: abc065ff2fb3
Revises: 6b52b1e7680b
Create Date: 2020-08-25 05:24:01.730596

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "abc065ff2fb3"
down_revision = "6b52b1e7680b"
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Apply the current migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("bot", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert the current migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "bot")
    # ### end Alembic commands ###
