"""add is_deleted to Message

Revision ID: d052a6b677e6
Revises: aa3517f1b1bd
Create Date: 2020-10-18 19:20:20.862476

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd052a6b677e6'
down_revision = 'aa3517f1b1bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'is_deleted')
    # ### end Alembic commands ###
