"""Add Discord.py 2.0 avatar support

Revision ID: d6c9452c3940
Revises: 911049796159
Create Date: 2021-10-31 12:48:03.323113

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6c9452c3940'
down_revision = '911049796159'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('guild_avatar_hash', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'guild_avatar_hash')
    # ### end Alembic commands ###
