name: Deploy to production

on:
  push:
    branches:
      - master

jobs:
  push_docker_image:
    name: Build & Publish Docker image
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build . --file Dockerfile -t python-discord/metricity/metricity:latest

      - name: Publish Docker image
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: python-discord/metricity/metricity:latest
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com

  trigger_autodeploy:
    name: Trigger Auto-Deploy
    runs-on: ubuntu-latest

    needs: [push_docker_image]

    steps:
      - name: curl
        uses: wei/curl@v1
        with:
          args: -X POST ${{ secrets.AUTODEPLOY_URL }}
